class Country {
  String countryLabel;
  String flagImageUrl;

  //Country(this.countryLabel, this.flagImageUrl,);

  int amount;
  List<CurrencyFx> currencyFx;

  Country(this.countryLabel, this.flagImageUrl, this.amount, this.currencyFx);

  static List<Country> samples = [
    Country(
      'Albania',
      'assets/albania.jpeg',
      1,
      [
        CurrencyFx('ALL', 1,),
        CurrencyFx('BRL', 0.054,),
        CurrencyFx('CNY', 0.61,),
        CurrencyFx('EUR', 0.0082,),
        CurrencyFx('EUR', 0.0082,),
        CurrencyFx('EUR', 0.0082,),
        CurrencyFx('JPY', 1.09,),
        CurrencyFx('MYR', 0.040,),
        CurrencyFx('RUB', 0.67,),
        CurrencyFx('SAR', 0.036,),
        CurrencyFx('GBP', 0.0070,),
        CurrencyFx('USD', 0.0096,),
        CurrencyFx('VND', 218.06,),
      ],
    ),
    Country(
      'Brazil',
      'assets/brazil.jpeg',
        1,
        [
          CurrencyFx('ALL', 18.47,),
          CurrencyFx('BRL', 1,),
          CurrencyFx('CNY', 1.13,),
          CurrencyFx('EUR', 0.15,),
          CurrencyFx('EUR', 0.15,),
          CurrencyFx('EUR', 0.15,),
          CurrencyFx('JPY', 20.10,),
          CurrencyFx('MYR', 0.73,),
          CurrencyFx('RUB', 12.45,),
          CurrencyFx('SAR', 0.66,),
          CurrencyFx('GBP', 0.13,),
          CurrencyFx('USD', 0.18,),
          CurrencyFx('VND', 4027.07,),
        ],
    ),
    Country(
      'China',
      'assets/china.jpeg',
      1,
      [
        CurrencyFx('ALL', 16.34,),
        CurrencyFx('BRL', 0.88,),
        CurrencyFx('CNY', 1,),
        CurrencyFx('EUR', 0.13,),
        CurrencyFx('EUR', 0.13,),
        CurrencyFx('EUR', 0.13,),
        CurrencyFx('JPY', 17.79,),
        CurrencyFx('MYR', 0.65,),
        CurrencyFx('RUB', 11.01,),
        CurrencyFx('SAR', 0.59,),
        CurrencyFx('GBP', 0.11,),
        CurrencyFx('USD', 0.16,),
        CurrencyFx('VND', 3563.80,),
      ],
    ),
    Country(
      'Europe',
      'assets/europe.jpg',
      1,
      [
        CurrencyFx('ALL', 121.51,),
        CurrencyFx('BRL', 6.58,),
        CurrencyFx('CNY', 7.43,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('JPY', 132.16,),
        CurrencyFx('MYR', 4.83,),
        CurrencyFx('RUB', 81.93,),
        CurrencyFx('SAR', 4.37,),
        CurrencyFx('GBP', 0.85,),
        CurrencyFx('USD', 1.16,),
        CurrencyFx('VND', 26495.45,),
      ],
    ),
    Country(
      'France',
      'assets/france.jpeg',
      1,
      [
        CurrencyFx('ALL', 121.51,),
        CurrencyFx('BRL', 6.58,),
        CurrencyFx('CNY', 7.43,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('JPY', 132.16,),
        CurrencyFx('MYR', 4.83,),
        CurrencyFx('RUB', 81.93,),
        CurrencyFx('SAR', 4.37,),
        CurrencyFx('GBP', 0.85,),
        CurrencyFx('USD', 1.16,),
        CurrencyFx('VND', 26495.45,),
      ],
    ),
    Country(
      'Germany',
      'assets/germany.jpeg',
      1,
      [
        CurrencyFx('ALL', 121.51,),
        CurrencyFx('BRL', 6.58,),
        CurrencyFx('CNY', 7.43,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('EUR', 1,),
        CurrencyFx('JPY', 132.16,),
        CurrencyFx('MYR', 4.83,),
        CurrencyFx('RUB', 81.93,),
        CurrencyFx('SAR', 4.37,),
        CurrencyFx('GBP', 0.85,),
        CurrencyFx('USD', 1.16,),
        CurrencyFx('VND', 26495.45,),
      ],
    ),
    Country(
      'Japan',
      'assets/japan.jpeg',
      1,
      [
        CurrencyFx('ALL', 0.92,),
        CurrencyFx('BRL', 0.050,),
        CurrencyFx('CNY', 0.056,),
        CurrencyFx('EUR', 0.0076,),
        CurrencyFx('EUR', 0.0076,),
        CurrencyFx('EUR', 0.0076,),
        CurrencyFx('JPY', 1,),
        CurrencyFx('MYR', 0.037,),
        CurrencyFx('RUB', 0.62,),
        CurrencyFx('SAR', 0.033,),
        CurrencyFx('GBP', 0.0064,),
        CurrencyFx('USD', 0.0088,),
        CurrencyFx('VND', 200.52,),
      ],
    ),
    Country(
      'Malaysia',
      'assets/malaysia.jpeg',
      1,
      [
        CurrencyFx('ALL', 25.14,),
        CurrencyFx('BRL', 1.36,),
        CurrencyFx('CNY', 1.54,),
        CurrencyFx('EUR', 0.21,),
        CurrencyFx('EUR', 0.21,),
        CurrencyFx('EUR', 0.21,),
        CurrencyFx('JPY', 27.37,),
        CurrencyFx('MYR', 1,),
        CurrencyFx('RUB', 16.95,),
        CurrencyFx('SAR', 0.90,),
        CurrencyFx('GBP', 0.18,),
        CurrencyFx('USD', 0.24,),
        CurrencyFx('VND', 5483.01,),
      ],
    ),
    Country(
      'Russia',
      'assets/russia.jpeg',
      1,
      [
        CurrencyFx('ALL', 1.48,),
        CurrencyFx('BRL', 0.080,),
        CurrencyFx('CNY', 0.091,),
        CurrencyFx('EUR', 0.012,),
        CurrencyFx('EUR', 0.012,),
        CurrencyFx('EUR', 0.012,),
        CurrencyFx('JPY', 1.61,),
        CurrencyFx('MYR', 0.059,),
        CurrencyFx('RUB', 1,),
        CurrencyFx('SAR', 0.053,),
        CurrencyFx('GBP', 0.010,),
        CurrencyFx('USD', 0.014,),
        CurrencyFx('VND', 323.70,),
      ],
    ),
    Country(
      'Saudi Arabia',
      'assets/saudi-arabia.jpeg',
      1,
      [
        CurrencyFx('ALL', 27.82,),
        CurrencyFx('BRL', 1.51,),
        CurrencyFx('CNY', 1.70,),
        CurrencyFx('EUR', 0.23,),
        CurrencyFx('EUR', 0.23,),
        CurrencyFx('EUR', 0.23,),
        CurrencyFx('JPY', 30.28,),
        CurrencyFx('MYR', 1.11,),
        CurrencyFx('RUB', 18.76,),
        CurrencyFx('SAR', 1,),
        CurrencyFx('GBP', 0.19,),
        CurrencyFx('USD', 0.27,),
        CurrencyFx('VND', 6066.61,),
      ],
    ),
    Country(
      'United Kingdom',
      'assets/united_kingdom.jpeg',
      1,
      [
        CurrencyFx('ALL', 143.59,),
        CurrencyFx('BRL', 7.77,),
        CurrencyFx('CNY', 8.79,),
        CurrencyFx('EUR', 1.18,),
        CurrencyFx('EUR', 1.18,),
        CurrencyFx('EUR', 1.18,),
        CurrencyFx('JPY', 156.27,),
        CurrencyFx('MYR', 5.71,),
        CurrencyFx('RUB', 96.82,),
        CurrencyFx('SAR', 5.16,),
        CurrencyFx('GBP', 1,),
        CurrencyFx('USD', 1.38,),
        CurrencyFx('VND', 31310.17,),
      ],
    ),
    Country(
      'United States of America',
      'assets/united_states_america.jpeg',
      1,
      [
        CurrencyFx('ALL', 104.35,),
        CurrencyFx('BRL', 5.65,),
        CurrencyFx('CNY', 6.38,),
        CurrencyFx('EUR', 0.86,),
        CurrencyFx('EUR', 0.86,),
        CurrencyFx('EUR', 0.86,),
        CurrencyFx('JPY', 113.57,),
        CurrencyFx('MYR', 4.15,),
        CurrencyFx('RUB', 70.36,),
        CurrencyFx('SAR', 3.75,),
        CurrencyFx('GBP', 0.73,),
        CurrencyFx('USD', 1,),
        CurrencyFx('VND', 22754.50,),
      ],
    ),
    Country(
      'Vietnam',
      'assets/vietnam.jpeg',
      1,
      [
        CurrencyFx('ALL', 0.0046,),
        CurrencyFx('BRL', 0.00025,),
        CurrencyFx('CNY', 0.00028,),
        CurrencyFx('EUR', 0.000038,),
        CurrencyFx('EUR', 0.000038,),
        CurrencyFx('EUR', 0.000038,),
        CurrencyFx('JPY', 0.0050,),
        CurrencyFx('MYR', 0.00018,),
        CurrencyFx('RUB', 0.0031,),
        CurrencyFx('SAR', 0.00016,),
        CurrencyFx('GBP', 0.000032,),
        CurrencyFx('USD', 0.000044,),
        CurrencyFx('VND', 1,),
      ],
    ),
  ];
}

class CurrencyFx {
  String currencyCode;
  double exRate;

  CurrencyFx (
      this.currencyCode,
      this.exRate,
      );

}